### ISSUE TITLE
Support App+Web Hits

### ISSUE THREAD

**Issue by pschneider87** [sean-adams/dataslayer#101]
As you know, with App+Web Properties, Google introduced the new Firebase DataModel for GA.

Hits request will look like
`https://www.google-analytics.com/g/collect?v=2&tid=G-X6LMX9VR0Y&gtm=2oeav3&_p=2097893835&sr=1920x1080&ul=de-de&cid=714123887.1545133496&_s=1&en=page_view&ep.page_path=%2Fanalytics%2Fweb%2Freport%2Fvisitors-legacy-user-id%2F&dl=https%3A%2F%2Fanalytics.google.com%2Fanalytics%2Fweb%2F%3Fhl%3Dde%26pli%3D1&dr=&dt=Analytics%C2%A0360&sid=1573685272&sct=395&seg=1`

This is from the GA Interface, where Google is already measuring with the new App+Web.
I'd love to have App+Web Support in DataSlayer as well for debugging.

If you need help for "translating" the Parameters, I'm happy to contribute

**Comment by pschneider87** [comment]
polite bump on this, since GA4 is the new standard - according to Google ;-)
As said, if there can help with translation, please reach out to me

**Comment by sean-adams** [comment]
Hi @pschneider87 sorry for letting this fall behind, I've had much less time to work on dataslayer this year. Would you mind taking a look to see if the new 1.3.7 version released to Chrome store today (and Firefox store shortly) displays these hits appropriately? And updating this issue to let me know?

**Comment by pschneider87** [comment]
hi @sean-adams, thanks for the heads up. I understand that this is your free time and I really appreciate your work in this area - saves me a lot of work each day!

I've tested the new version, but there seem to be no hits from Google Analytics 4 at the moment:

The GA4 hits look like 
`https://analytics.google.com/g/collect?v=2&tid=G-CGGTSWBS8W&gtm=2oeb41&_p=519868711&sr=1920x1080&ul=de-de&cid=1258430090.1585734532&_s=1&dl=https%3A%2F%2Fresolutionmedia.de%2F&dr=&dt=Performance%20Marketing%20Agentur%20%7C%20Resolution%20Media&sid=1606833347&sct=12&seg=1&en=page_view&ep.page=resolutionmedia.de%2F&ep.page_type=website&ep.container_version=24&ep.content_group1=homepage&ep.content_group2=website`

So first, they have a different endpoint than Universal Analytics and can be identified by v=2
Most important would be to display the Measurement ID (tid) and the Events (en) itself with their Parameters (ep.XYZ)

What could be imporant: GA4 batches hits together, so in one request there could be different events, the request url will be
`https://analytics.google.com/g/collect?v=2&tid=G-CGGTSWBS8W&gtm=2oeb41&_p=1272274545&sr=1920x1080&ul=de-de&cid=1258430090.1585734532&dl=https%3A%2F%2Fresolutionmedia.de%2F&dr=&dt=Performance%20Marketing%20Agentur%20%7C%20Resolution%20Media&sid=1606833347&sct=12&seg=1&_s=1`

Put the request has an additional payload:
```
en=page_view&ep.page=resolutionmedia.de%2F&ep.page_type=website&ep.container_version=24&ep.content_group1=homepage&ep.content_group2=website
en=scroll&_et=720&ep.page=resolutionmedia.de%2F&ep.page_type=website&ep.container_version=24&ep.content_group1=homepage&ep.content_group2=website&epn.percent_scrolled=90
```

en= Event Name
ep.XYZ = Event Parameter "XYZ" (multiple parameters are possible)
epn.XZY = numeric Event Parameter "XYZ" (multiple parameters are possible)

Hope that helps, let me know if I can help you debugging

**Comment by sean-adams** [comment]
Thanks @pschneider87 this is super helpful. I hadn't realized that the parameter format had changed so significantly in GA4, but I think an initial version of this shouldn't take too long to implement - hoping I will have time in the next week or so, mal sehen :)
By any chance would you be able to share a link to a working GA4 implementation I can debug against? If you'd like to share privately that's fine.

**Comment by pschneider87** [comment]
Awesome, sounds great. Feel free to reach out to me if you need any help

You can take https://resolutionmedia.de or debug in the Google Analytics interface itself, they have implemented GA4 already.

**Comment by sean-adams** [comment]
Hi @pschneider87 initial support for App+Web will be included in version 1.4.0 which should be releasing to the Chrome store soon. Would love to get your feedback!

**Comment by pschneider87** [comment]
@sean-adams awesome job, works great.
Some possible improvements:

- app&web was the project name, Google now officially calls it "Google Analytics 4"
- - change in settings
- - change in the hit-parser after Measurement ID

- "user parameters" are officially called "user properties"

- Enhanced Ecommerce is also implemented with prX (e.g. pr1, pr2, etc.) and further Information in a string
nm = Product Name
id = Product ID
pr = Price
br = Brand
ca = Category
va = Variant
lp = List Position
ln = List Name

Request looks like this, item parameters are separated by ~
pr1=nmShirt%20black~id2216~pr74.49~brMyFashion~caShirts~va11302000299~lp1~lnhomepage&pr2=...

Expandable fields for Products, maybe with ProductName as the top-value would be awesome

**Comment by sean-adams** [comment]
Thanks @pschneider87 as always, this is incredibly helpful. Will work on another iteration and get it out ASAP :+1:
