### ISSUE TITLE
DataSlayer won't open in latest Chrome Versions

### ISSUE THREAD

**Issue by pschneider87** [sean-adams/dataslayer#109]
running Chrome Version 83.0.4103.97 (Offizieller Build) (64-Bit), dataSlayer won't open in DEV Tools.
It takes a view times opening and closing the dev tools, until dataSlayer shows up.

**Comment by NLW-paulm** [comment]
Im getting the same issue, Dataslayer is injecting launch monitors, but the tab does not appear in dev tools to see the results, See screenshot attached.

![Desktop_screenshot](https://user-images.githubusercontent.com/13763736/84133962-c69c1200-aa3f-11ea-839f-a9ddaf46ac9a.png)

**Comment by sean-adams** [comment]
@pschneider87 @NLW-paulm thanks for bringing this to my attention - I'm investigating and hope to provide an update soon!

**Comment by sean-adams** [comment]
Unfortunately this appears to be a known issue in Chrome 83.0.4103+:
https://bugs.chromium.org/p/chromium/issues/detail?id=1093731

From the comments, it seems like it tends to be triggered by opening devtools for the first time while a heavy page is loading - a suggested workaround that seems to fix this for me is opening devtools while on a new (empty) tab and *then* navigating to the site you want to inspect. Can you let me know if this solves the issue for you?

**Comment by pschneider87** [comment]
yes, I can replicate this behaviour. Furthermore, starting with a fresh opened chrome session is also helpfull. Good to know that it's on the chromium teams radar.

**Comment by CyBrian** [comment]
Hi
Thank you for dataSlayer and for supporting it
I'm using Chrome Version 83.0.4103.106 (Official Build) (64-bit)

The suggested workaround does not work for me

**Comment by pschneider87** [comment]
seems to be fixed with latest chrome versions, at least I did not notice this problem anymore.
