### ISSUE TITLE
can't get Dataslayer to show UA codes in Firefox 80

### ISSUE THREAD

**Issue by Faust-616** [sean-adams/dataslayer#113]
On a website whose source code shows its Google Analytics UA code,  Dataslayer shows a red X and nothing else.  To my knowledge, I've not opted out of Google Analytics.  Any ideas?

![1](https://user-images.githubusercontent.com/70860631/92334724-4b55f680-f056-11ea-9dd0-c9f9e66d035c.png)

**Comment by sean-adams** [comment]
Sorry for the delayed response here @Faust-616 , I've identified this issue and will be releasing a fix ASAP

**Comment by Faust-616** [comment]
Thanks! Works great now!
