### ISSUE TITLE
dataSlayer is not recording GA hits sent with POST

### ISSUE THREAD

**Issue by CyBrian** [sean-adams/dataslayer#116]
e.g. I load a page and Network tab shows 3 pageviews (tagging is in development!!!)

If GA sends all 3 hits using GET, all 3 are reported
If one is sent with POST and 2 using GET, only the GET pageviews are reported by dataSlayer
The Network tab reports all 3

In the attached image, the 3 pageviews report via a GET and the event by POST and the latter is the one that dataSlayer is not reporting.
It does not appear to relate to the size of the request because I had bloated the request previously to force all hits to send via POST. Strangely, dataSlayer reported all those hits

dataSlayer is showing all the dataLayer updates that trigger the hits whether it reports them or not.

I un-/reinstalled dataSlayer to ensure I had the latest version - made no difference

Google Chrome is up to date
Version 87.0.4280.66 (Official Build) (64-bit)

Running Windows 10

![del_dataSlayerCap](https://user-images.githubusercontent.com/12588635/100536987-5d6cae80-31d9-11eb-90b0-a28e43453abb.GIF)

**Comment by sean-adams** [comment]
Seems like GA is using a new, slightly different endpoint that dataslayer wasn't catching - I've identified a fix and will be releasing ASAP. Thanks for flagging

**Comment by sean-adams** [comment]
This should be resolved in version 1.3.7 released to the Chrome store today and releasing to Firefox store shortly.
