### ISSUE TITLE
Cannot have future date range

### ISSUE THREAD

**Issue by daveshow93** [sean-adams/dataslayer#125]
Hi all

I have a report that the date range is from 1 November 2020 to 30th September 2021. This used to work nicely and I would just hit refresh on my query and it would update every day.

However now it comes up with "Invalid parameters combination" error.
![image](https://user-images.githubusercontent.com/79463890/108725003-d603b280-751d-11eb-8b33-70dcaaffa2d1.png)

Is there any way of creating a report with a date range going into the future? Or do I have to change the date parameters each day?

Thanks!

**Comment by sean-adams** [comment]
Hi @daveshow93, unfortunately it seems that you are looking for support for https://www.dataslayer.ai/ - this is completely unrelated to this repo, which is for the Chrome extension https://dataslayer.org/ that I have been providing for several years. Bummer that dataslayer.ai seems to have caused this confusion by using the same name :slightly_frowning_face:
