### ISSUE TITLE
Chrome disabled dataSlayer in 89.0.4389.114 

### ISSUE THREAD

**Issue by KrisMJ** [sean-adams/dataslayer#128]
As of this morning, we are unable to access data slayer from Chrome

This extension may be dangerous
The extension "dataslayer" was automatically disabled

**Comment by smallm2** [comment]
Having same issue.

**Comment by sean-adams** [comment]
Hi all, thanks for sharing this, I'm seeing this as well and have reached out to Google for more information.

**Comment by sean-adams** [comment]
In the short term, while it's not ideal to have to change your browser, dataslayer is also available for Firefox: https://addons.mozilla.org/en-US/firefox/addon/dataslayer-firefox/

**Comment by smallm2** [comment]
Thanks Sean, unfortunately due to compny policy Firefiox is not enabled on our laptops.  We must use Chrome currently.

**Comment by sean-adams** [comment]
Sorry to hear that @smallm2 . I'm guessing your company policy won't let you do this either, but it's possible to build dataslayer from the source code and load it locally as an unpacked extension:
https://github.com/sean-adams/dataslayer#developing

Sorry again for this issue, unfortunately I have no insight yet from Google / Chrome Web Store team.

**Comment by sean-adams** [comment]
Quick update here, I eventually received a notification of the specific reason dataslayer was removed from the Chrome Web Store (requesting overly broad permissions, notably `tabs` permission which was apparently not actually needed to use the `chrome.tabs` API). I've rectified the violation (by removing the request for `tabs` permission, as visible in https://github.com/sean-adams/dataslayer/pull/129) and resubmitted and will update this thread again when it has been re-reviewed.

**Comment by KrisMJ** [comment]
It magically started working around 445 pm local today. Much enthusiasm was expressed.  THANK YOU

Kristin Johnson
Google Analytics Analyst
***@***.***

________________________________

**Comment by sean-adams** [comment]
Happy to hear it!! Unfortunately it's still unavailable for installation via the web store, but I hope that's resolved soon as well!

**Comment by smallm2** [comment]
Sean -thanks – working here too this afternoon!! Thanks so much for the Amazingly fast fix!

Melissa Smallenberger
Principal Software Engineer

**Comment by sean-adams** [comment]
dataslayer is now back in the Chrome Web Store: https://chrome.google.com/webstore/detail/dataslayer/ikbablmmjldhamhcldjjigniffkkjgpo
