### ISSUE TITLE
Content Groups for ga.js

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [sean-adams/dataslayer#28]
While named Page Group, Content Grouping also exists in ga.js
https://support.google.com/analytics/answer/2853546?hl=en

Sample hit
http://stats.g.doubleclick.net/__utm.gif?utmwv=5.6.2dcd&utms=1&utmn=180210171&utmhn=www.auchan.fr&utme=8(utma*rcw*4!autre)9(165340000.2091847200.1422010803*anonymous*4!no)11(1*1*4!2)&utmcs=UTF-8&utmsr=1600x900&utmvp=1517x839&utmsc=24-bit&utmul=fr&utmje=1&utmfl=16.0%20r0&utmdt=Meuble%20et%20literie%20%C3%A0%20prix%20Auchan%20%3A%20pas%20cher%20et%20discount&utmhid=866939462&utmr=-&utmp=%2Fsoldes%2Fmeuble-et-literie%2Fc-13367097&utmpg=1:8621163-soldes,2:13367097-meuble_et_literie&utmht=1422388097172&utmac=UA-2008294-1&utmcc=__utma%3D165340000.2091847200.1422010803.1422385003.1422388097.3%3B%2B__utmz%3D165340000.1422010803.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B%2B__utmv%3D165340000.hybris%3B&utmu=qTEAgAAAAAAAAAAAAgAAABB~

on this page http://www.auchan.fr/soldes/meuble-et-literie/c-13367097

utmpg:1:8621163-soldes,2:13367097-meuble_et_literie

Parsing doesn't work in version 0.10.0

Thanks for your attention

**Comment by sean-adams** [comment]
Fixed in 39dd28b
