### ISSUE TITLE
Object value "object" instead of "null"

### ISSUE THREAD

**Issue by woutervandiggelen** [sean-adams/dataslayer#29]
My dataLayer contains several objects with value "null" but in the dataslayer tab the values are displayed as "object". I expect to see "null" here.
![dataslayer](https://cloud.githubusercontent.com/assets/10907378/6106274/5b5ff1c0-b060-11e4-89c8-e028a76f344e.png)

**Comment by sean-adams** [comment]
In your screenshot is e.g. Application.Errors null?

**Comment by woutervandiggelen** [comment]
Yes

**Comment by sean-adams** [comment]
Closed in release 0.10.3, commit 7e3454771b73a50da2c6482a36ea83ef851c6991
