### ISSUE TITLE
Request: add gtm.elementText to GTM Auto-Event dataLayer values shown

### ISSUE THREAD

**Issue by camrodam** [sean-adams/dataslayer#30]
Currently dataSlayer does not show the "Click Text" Variable value of gtm.click, formsubmit or linkclick events:
![image](https://cloud.githubusercontent.com/assets/4508900/9063648/da4f6162-3ac8-11e5-8b57-954cc948e1e5.png)

Would be easier, since GTM offers it as a built-in Variable:
![image](https://cloud.githubusercontent.com/assets/4508900/9063768/7df39784-3ac9-11e5-8a98-3e7228cf8048.png)

**Comment by sean-adams** [comment]
Fixed in 3bef41
