### ISSUE TITLE
dataLayer values with HTML entities get displayed decoded which is misleading

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [sean-adams/dataslayer#31]
We had a value of 'rappel&eacute;' in a object attribute value, dataslayer showed 'rappelé' instead of the true value.
The, when trying to create rules based on this value, GTM didn't fire since the value shown by dataslayer wasn't the true one.
Can you prevent dataslayer from unescaping those strings ?

**Comment by sean-adams** [comment]
@googleanalyticsresoneo can you please provide a test case?

**Comment by googleanalyticsresoneo** [comment]
Hi

If you push this
  window.dataLayer.push({
        "environment_dnt": "n",
        "environment_work": "prod",
        "cart_id" : "",
        "checkout_type" : "classic",
        "page_type": pageType,
        "page_cat1": "Arts de la table",
        "page_cat2": "Couvert et m&eacute;nag&egrave;re",
        "page_cat3": "M&eacute;nag&egrave;re",
        "page_cat1Id": "67",
        "page_cat2Id": "1504",
        "page_cat3Id": "1508",
		"event":"dataReady"
		};

datasLayer will show **decoded** entities, while if you push those values to Google Analytics for example, you'll get the raw values.
Then it's important to detect those cases where HTML entities are present in values, and to see them in raw format in the datasLayer panel

Maybe have a look to escapeHTML in http://stackoverflow.com/a/9251169 ?

Thanks very much for looking into this

**Comment by sean-adams** [comment]
Only took a few years :) A setting for this will be in release 1.1.
