### ISSUE TITLE
'Object.observe' is deprecated 

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [sean-adams/dataslayer#32]
Seen in Google Chrome Console : 

'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

**Comment by googleanalyticsresoneo** [comment]
Some alternative options exposed here https://esdiscuss.org/topic/an-update-on-object-observe

**Comment by sean-adams** [comment]
Thanks @googleanalyticsresoneo , sorry for the late response-- this should be fixed in 0.10.12 which is releasing shortly.
