### ISSUE TITLE
datalayer panel broken in newest version of chrome

### ISSUE THREAD

**Issue by daniellewooding** [sean-adams/dataslayer#34]
I'm in chrome 50.0.2661.94 and dataslayer version 10.8.

I'm working on a client site where I'm debugging a datalayer and omniture using dataslayer where one ends up on the left and one on the right in the tool. This was working great until chrome updated. Now I'm getting an error. I'm still able to see the omniture data on the right, but the datalayer data is missing from the left and the console is throwing an error:

![5-4-2016 4-16-18 pm](https://cloud.githubusercontent.com/assets/7399293/15027806/93ce4afa-1213-11e6-9ed7-b1d441172f7f.png)

Uncaught Type:Error: Object.observe is not a function. 

This may be related to the deprecation of this function that another issue notes.

**Comment by sean-adams** [comment]
Hi Danielle, thanks for flagging this--  this should be fixed in 0.10.12 which is releasing shortly.
