### ISSUE TITLE
Question: Why the dataLayer is not visible for some websites, even though I can see it via the console?

### ISSUE THREAD

**Issue by varun-patil-rocket** [sean-adams/dataslayer#36]
Hey, Sean! First of all, great add-on. Thanks a lot for the work you put in! 

I tried looking at the dataLayer for websites such as http://www.lamoda.by/ or nested.com, however, for some reason, the dataLayer is not visible in dataslayer, even though I can see the dataLayer in the console. E.g.:

![image](https://cloud.githubusercontent.com/assets/18722313/18833790/b609c1d4-83f2-11e6-8bf1-0b7c7f8f93a8.png)

Thanks!

**Comment by sean-adams** [comment]
Hi @varun-patil-rocket -- it appears that there are two different issues here:
Lamoda: GTM is loaded after the page has completely finished loading, so dataslayer has already stopped looking for GTM. I'm not sure if there is a great fix for this, as we have to manually search for GTM using a timer, which degrades performance of the page if we run it indefinitely.
Nested: In this case, changes to the params in loading GTM have made dataslayer look in the wrong place for a manually set dataLayer variable name. I'm working on a fix for this and hope to roll it out soon!

**Comment by sean-adams** [comment]
The issue with Nested has been resolved in 0.10.13 which is rolling out now.

**Comment by varun-patil-rocket** [comment]
Thanks a ton, Sean! Checked nested again. Works super smooth!
