### ISSUE TITLE
dataslayer 

### ISSUE THREAD

**Issue by sandye7** [sean-adams/dataslayer#37]
crashed and won't track in chrome.

**Comment by sean-adams** [comment]
@sandye7 is this on all pages, or with specific site(s)?

**Comment by sandye7** [comment]
all pages

*Sandye **Sowers* <http://www.cognizant.com/cognizant-interactive>

NERD LIFE...ME ALL DAY! <http://youtu.be/Op1i0B8-dJA>

*What is web analytics?*  *It turns out that the answer is both simple and
loaded: web analytics is pretty much everything.  It’s a multi-discipline
practice that aims to quantify today’s success and uncover usability,
design, architecture, copy, product, and marketing optimizations that will
breed even more success tomorrow for your business. I'm very happy that a
hybrid like myself  can now do the happy dance because most business get
it...** analytics is an art form. *

*********************************************************************
The research space has been "revolutionized over time" It's not about user,
brand, media, market or consumer research silos. Rather, it's about
integrated, ever-present, sustainable insights that tap into deep human
connections and behaviors that tell powerful stories and drive business
results.
*Chad Maxwell* @ Starcom



http://www.atlantaanalytics.com

ADOBE TV- SiteCatalyst  <http://adobe.ly/IUEULb>

**Comment by sean-adams** [comment]
@sandye7 what version of Chrome, and what version of dataslayer, are you using? Can you try uninstalling and reinstalling dataslayer and see if that works?
