### ISSUE TITLE
Dataslayer is breaking in the UK

### ISSUE THREAD

**Issue by PeterLeapThree** [sean-adams/dataslayer#40]
Hi Sean,

First, we have found Dataslayer to be a great tool, it is used extensively by the team here at LeapThree and we have many of our clients using it too.  But in the last few weeks, it appears to have developed a bug in that while the GA tags are still recorded properly, the pages don't update (as in a new set of data layer & GA calls) and the Data Layer stops recording.  

I have asked the question on twitter and it is working fine for contacts elsewhere in Europe.  But our clients have raised the same issues with us, not sure why good for some but not others.  I have deleted all other extensions & reinstalled but no luck.  Issue is across all websites.  One of the contacts in Switzerland (I am in the UK) who is having no issues with dataslayer has the exact same Chrome version of me as well.

This is where I need to admit I just thought of this as a great free tool, not something that someone had built and we should be paying for.  If you could investigate and get working again, happy to make a contribution plus to put the call out through to MeasureCamp community for other users to contribute too - in case this helps.

Let me know if I can provide any other details to help.

Peter

**Comment by PeterLeapThree** [comment]
Hi Sean,

Thanks for coming back to me & so quickly, really appreciate it.  This was getting annoying for me but when our clients starting voicing their frustrations, had to reach out.

First caveat is I am not a developer, hence why dataslayer is so good for me.  Trying to get at the information you need but apologies if I can’t get it right initially.  I am about to head to bed now but if you send follow up questions through, I can take a screenshare video tomorrow and/or enlist a developer friend help to provide you with exactly the information you need.

Chrome version is Version 65.0.3325.181 (Official Build) (64-bit) but this doesn’t appear to be the issue as a contact is also on the exact same version and it is working fine.

After hitting issues with every website recently, I just manged to get through a few different page views without a problem, it was only when I triggered an event that it all went wrong.  My testing is with www.visiondirect.co.uk<http://www.visiondirect.co.uk>.  It appears to be fine when I am clicking between pages but breaks as soon as I add contact lenses to the basket (last page displayed is the product page, GA tags continue to be recorded).

No relevant console errors that appear relevant.  But when I followed your instructions, I get the two error messages below.  The targetDate.getTime error appears repeatedly, that doesn’t appear to be an issue.

But the _resources issue is only triggered when dataslayer stops working.  Hopefully that helps pinpoint the issue.  Wondering if related to the way we use the data layer & GTM/GA with our clients if affecting us & maybe not others.

Let me know if I can drill deeper into the details for you.

Regards

Peter



[cid:image001.png@01D3D1E5.C0496DB0]


Peter O’Neill
Director
LeapThree

Mobile: +44 7843 617347
Website: www.leapthree.com<http://www.leapthree.com/>
Twitter: @peter_oneill<https://twitter.com/peter_oneill>

[cid:image003.jpg@01D3D1E6.3C9E7FE0]

LeapThree is the proud organiser of the DA Hub analytics and optimisation conference.
The 2018 DA Hub will take place at the Sheraton Austin Texas, October 17th – 19th.
www.digitalanalyticshub.com<http://www.digitalanalyticshub.com/>

**Comment by sean-adams** [comment]
@PeterLeapThree 
Hi Peter,
Looks like the images didn't come through to GitHub - can you please send them via email to dataslayer@bearcla.ws ? That being said, I was able to replicate your issue on visiondirect.co.uk and it appears that this may be due to a Chrome bug introduced in version 65 that affects how certain cookies are processed: https://bugs.chromium.org/p/chromium/issues/detail?id=801306 [not sure this will help you as a non-developer 😄 but good to know it has been flagged on their side]
At this point whether or not dataslayer works is dependent on how various sites and their third-party trackers, etc. implement cookies - very frustrating! I'm going to start looking into workarounds while hopefully the Chromium team is working on fixing the bug :)

Best
Sean

**Comment by sean-adams** [comment]
Update: this issue appears to be fixed in the Chrome beta channel, and the alternate APIs available aren't as suitable for dataslayer's needs as the broken APIs are, so for the time being I'm going to recommend switching to the beta channel: https://www.google.com/chrome/browser/beta.html

**Comment by PeterLeapThree** [comment]
Hi Sean,

That works for me as a solution, have just downloaded the beta version of Chrome & can see dataslayer working fine there – I can use that as our debugging tool.  Thanks very much for looking into this for me.

Regards

Peter



Peter O’Neill
Director
LeapThree

Mobile: +44 7843 617347
Website: www.leapthree.com<http://www.leapthree.com/>
Twitter: @peter_oneill<https://twitter.com/peter_oneill>

[cid:image002.jpg@01D3D2FF.23DA0320]

LeapThree is the proud organiser of the DA Hub analytics and optimisation conference.
The 2018 DA Hub will take place at the Sheraton Austin Texas, October 17th – 19th.
www.digitalanalyticshub.com<http://www.digitalanalyticshub.com/>
