### ISSUE TITLE
Highlight non interactive hit value, or any custom parameter

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [sean-adams/dataslayer#43]
The nonInteractive option can be really important to preserve proper bounce rate tracking.
It would be helpful to add a row for that value, instead of requiring to expand the full list of parameters to have a look at it

Another approach could be to allow monitoring of custom parameter in datasLayer config page: when adding 'ni', it would add a row with 'ni' and its value, only when its present

**Comment by sean-adams** [comment]
In 1.0, non-interactive will be displayed by default whenever it is set.
