### ISSUE TITLE
Adobe calls have dissapeared from Data Slayer?

### ISSUE THREAD

**Issue by ObieWanKanobi** [sean-adams/dataslayer#44]
Hi,

I used to get the Adobe calls presented next to the data layer. Since some time back, these Adobe calls are no longer visible, I can only see the data layer info. Google Analytics still show up as normal and my settings are set to show both Adobe and GA. Still works on my colleague's machine, running on the same version of Chrome but with a different OS.  

Best,
Tobias

**Comment by sean-adams** [comment]
Hi @ObieWanKanobi thanks for reporting this!
- Can you tell me what OS you're on and what OS your colleague is on? 
- Can you also try the following, when you expect to see an Adobe call but don't:
  - Right-click on the dataslayer panel and choose Inspect
  - In the new DevTools window that opens, switch to Console
  - Please share any console messages you see

Thanks again!

**Comment by Dischordant** [comment]
June Bug ir Cricket?

**Comment by sean-adams** [comment]
Closing this issue for now. If more info can be provided I'll be happy to reopen!
