### ISSUE TITLE
dataslayer Not capturing GA events

### ISSUE THREAD

**Issue by VipanGoja** [sean-adams/dataslayer#45]
Been noticing this for past 10-15 days. Requests to GTM are being shown but GA requests are not shown. I have checked data in GA and it shows as expected. Also, I do not have any ad-blocker installed on my system.

**Comment by sean-adams** [comment]
Hi @VipanGoja , thanks for submitting. Can you please provide the following information:
- Is this happening on all sites, or only specific sites? If only specific sites, can you share?
- What version of Chrome are you on? What OS are you on?
- Can you also try the following, when you expect to see a GA request but don't:
  - Right-click on the dataslayer panel and choose Inspect
  - In the new DevTools window that opens, switch to Console
  - Please share any console messages you see

**Comment by sean-adams** [comment]
Closing this issue for now. If more info can be provided I'll be happy to reopen!
