### ISSUE TITLE
Considering a Firefox version?

### ISSUE THREAD

**Issue by mkjeldsen** [sean-adams/dataslayer#48]
Hi Sean,

definitely not an issue , but I'm not sure where else to ask. So here goes:

**Are you considering making a version for Firefox?**

It would be much appreciated and I doubt I'm the first person who's looking for dataslayer functionality in Firefox :-)

m.

**Comment by mkjeldsen** [comment]
@sean-adams - anything on this? :-)

**Comment by sean-adams** [comment]
@mkjeldsen Consider this officially on my radar :) It looks like some of the APIs / devtools integration might make this slightly more complicated than your average port, but definitely agree it's worth it and on the roadmap.

**Comment by mkjeldsen** [comment]
@sean-adams 👏🏼

**Comment by sean-adams** [comment]
@mkjeldsen if you'd be interested in helping to test a Firefox beta, it would be much appreciated :slightly_smiling_face:

**Comment by sean-adams** [comment]
I did it, in juuuuust under a year :smile: 
https://addons.mozilla.org/en-US/firefox/addon/dataslayer-firefox/
1.3 will be the first official release in the next few days.
