### ISSUE TITLE
DataSlayer not loading on some Chrome profiles

### ISSUE THREAD

**Issue by Gidid** [sean-adams/dataslayer#49]
Hi There, 
I've been using dataslayer for a little while now, and it is awesome! However, I have it installed on few Chrome profiles (one chrome installation on Mac), and sometimes it does not load on the dev tools console. This seems to be affecting some profiles and not others, and I couldn't sort it out.
Tried to disable / re-enable and remove / reinstall - no luck there...

Thanks, 

Gidi

**Comment by sean-adams** [comment]
Hi @Gidid , are you still having this problem?

**Comment by sean-adams** [comment]
Closing this issue for now. If more info can be provided I'll be happy to reopen!
