### ISSUE TITLE
Feature Request: Filter for gtm.* event namespaced pushes

### ISSUE THREAD

**Issue by smhmic** [sean-adams/dataslayer#51]
GTM uses the datalayer for all their built-in listeners.  Add just a click trigger and a scroll depth trigger, and the datalayer can get really convoluted.

This could be addressed by adding color or some other visual indicator to differentiate GTM's internal pushes from everything else, or perhaps a show/hide toggle.

**Comment by sean-adams** [comment]
Added in 1.0
