### ISSUE TITLE
dataslayer stops recording after hitting an error

### ISSUE THREAD

**Issue by Rifmaz** [sean-adams/dataslayer#55]
Hi,

I am testing the new version of dataslayer (1.0.0) and it works fine until it reaches a page where the dataLayer pushes seem to be broken. Understandably, nothing is being shown as being sent to the dataLayer on these pages. However, if I then navigate to a page where the dataLayer works fine, dataslayer does not update any more.

It appears that once dataslayer hits the corrupted datalayer push, it is not able to move past and effectively stops tracking. I have to clear history on dataslayer to restart the tracking.

In case it helps, the error I get on Google Chrome console is:
Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by sean-adams** [comment]
Hi @Rifmaz, thank you for reporting this - is there any chance you can send me the URL for a site that triggers this behavior?
If you don't feel comfortable posting it publicly feel free to send to info@dataslayer.org
Thank you!
