### ISSUE TITLE
Not seeing custom data layer object of digitalData with new version

### ISSUE THREAD

**Issue by redboy73** [sean-adams/dataslayer#68]
Hi Sean, since the newest version of dataslayer has been released, I am not longer seeing my custom data layer object of digitalData being displayed in the UI, even though I have defined it in the 'Additional data layer objects' section as required. I can access it via the Console, so I know it's definitely there. Can you help?

Thanks, Mark

**Comment by sean-adams** [comment]
Hi Mark @redboy73 

Thanks for catching this - a dumb mistake by me, and will be fixed in version 1.1.1 releasing today.

Best
Sean

**Comment by redboy73** [comment]
No problem. Sounds good. Thanks Sean!
