### ISSUE TITLE
Malformed JSON in import

### ISSUE THREAD

**Issue by liteljaime** [sean-adams/dataslayer#72]
Hi Sean,

I'm trying to import JSON data previously exported from the tool but I'm getting this error message.

![image](https://user-images.githubusercontent.com/25181241/55957993-8be1f280-5c5f-11e9-809c-5ea858635e91.png)

Couldn't find information about the issue anywhere. Have you come across this before? Any idea how could I fix it?

Thanks,

J

**Comment by sean-adams** [comment]
Hi @liteljaime ,
Thanks for reporting this and sorry that there's an issue - if you don't mind, can you please share the JSON file? If you don't feel comfortable sharing it publicly, you can email to info@dataslayer.org

**Comment by sean-adams** [comment]
This was related to an issue with escaping characters in the export and will be fixed in 1.1.2.
