### ISSUE TITLE
What is PATH?

### ISSUE THREAD

**Issue by illia108** [sean-adams/dataslayer#74]
Hi. It's not an issue but rather a question. I'm debugging ga tracking and I noticed that it fires only when there is a PATH attribute in dataslayer. If it is just URL ga doesn't fire. Can you explain why some pages have path attribute and others don't? Thanks

**Comment by sean-adams** [comment]
Hi @illia108  - the Path attribute represents the Page Path / Document Path (dp) in a GA call.
